#define BLYNK_PRINT Serial // Comment this out to disable prints and save space

#include <ESP8266WiFi.h>

#include <BlynkSimpleEsp8266.h>

#include <DHT.h>

#include <SimpleTimer.h>

#define DHTPIN 0

#define DHTTYPE DHT11

DHT dht(DHTPIN, DHTTYPE);

SimpleTimer timer;

float humidity, temp_f; // Values read from sensor

char auth[] = ""; //insert here your token generated by Blynk

void setup()

{

Serial.begin(115200); // See the connection status in Serial Monitor

delay(10);

Blynk.begin(auth, "", ""); //insert here your SSID and password

timer.setInterval(1000, sendData);

pinMode(A0, OUTPUT);

}

void sendData()

{

//Read the Temp and Humidity from DHT

float h = dht.readHumidity();

float t = dht.readTemperature();

int mRAW = analogRead(A0);

int m = map(mRAW, 400, 3200, 0, 100);

//Write values to V04 and V05

Blynk.virtualWrite(1, h);

Blynk.virtualWrite(0, t);

Blynk.virtualWrite(2, m);

}

void loop()

{

Blynk.run();

timer.run();

}
